service: serverless-music-gear

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: handlers/api/products.create
    events:
      - http:
          path: products
          method: post
          cors: true

  list:
    handler: handlers/api/products.list
    events:
      - http:
          path: products
          method: get
          cors: true

  get:
    handler: handlers/api/products.get
    events:
      - http:
          path: products/{id}
          method: get
          cors: true

  update:
    handler: handlers/api/products.update
    events:
      - http:
          path: products/{id}
          method: put
          cors: true

  delete:
    handler: handlers/api/products.remove
    events:
      - http:
          path: products/{id}
          method: delete
          cors: true

resources:
  Resources: ${file(./resources/database.yml)}
